// WDC defines used for RTL-specific cases
{$IFDEF VER140} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi 6 compiler
{$IFDEF VER150} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi 7 compiler
{$IFDEF VER220} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE compiler
{$IFDEF VER230} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE2 compiler
{$IFDEF VER240} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE3 compiler
{$IFDEF VER250} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE4 compiler
{$IFDEF VER260} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE5 compiler
{$IFDEF VER270} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE6 compiler
{$IFDEF VER280} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE7 compiler
{$IFDEF VER290} {$DEFINE WDC} {$ENDIF} // Define Windows Delphi XE8 compiler